networks:
  appnet:

volumes:
  kafka1_data:
  kafka2_data:
  kafka3_data:

services:
  # -------------------------------
  # Kafka (KRaft) - 3 nodes
  # -------------------------------
  kafka-1:
    image: bitnamilegacy/kafka:3.6.2-debian-12-r17
    container_name: kafka-1
    networks: [appnet]
    volumes:
      - kafka1_data:/bitnami/kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_CLUSTER_ID=prod-messaging-cluster
      - KAFKA_KRAFT_CLUSTER_ID=prod-messaging-cluster
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT_INTERNAL://:9092,PLAINTEXT_EXTERNAL://:9094,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT_INTERNAL://kafka-1:9092,PLAINTEXT_EXTERNAL://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT_INTERNAL
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_CFG_MIN_INSYNC_REPLICAS=2
      - KAFKA_CFG_NUM_PARTITIONS=6
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      # Quota windows (responsive throttling)
      - KAFKA_CFG_QUOTA_WINDOW_NUM=10
      - KAFKA_CFG_QUOTA_WINDOW_SIZE_SECONDS=1
      # Recommended misc
      - KAFKA_CFG_MESSAGE_MAX_BYTES=10485760
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=11534336
      - KAFKA_CFG_FETCH_MESSAGE_MAX_BYTES=11534336
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_OFFSETS_TOPIC_MIN_ISR=2
    ports:
      - "29092:9094"   # host access

  kafka-2:
    image: bitnamilegacy/kafka:3.6.2-debian-12-r17
    container_name: kafka-2
    networks: [appnet]
    volumes:
      - kafka2_data:/bitnami/kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_CLUSTER_ID=prod-messaging-cluster
      - KAFKA_KRAFT_CLUSTER_ID=prod-messaging-cluster
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT_INTERNAL://:9092,PLAINTEXT_EXTERNAL://:9094,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT_INTERNAL://kafka-2:9092,PLAINTEXT_EXTERNAL://localhost:29093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT_INTERNAL
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_CFG_MIN_INSYNC_REPLICAS=2
      - KAFKA_CFG_NUM_PARTITIONS=6
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CFG_QUOTA_WINDOW_NUM=10
      - KAFKA_CFG_QUOTA_WINDOW_SIZE_SECONDS=1
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=11534336
      - KAFKA_CFG_FETCH_MESSAGE_MAX_BYTES=11534336
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_OFFSETS_TOPIC_MIN_ISR=2
    ports:
      - "29093:9094"   # host access

  kafka-3:
    image: bitnamilegacy/kafka:3.6.2-debian-12-r17
    container_name: kafka-3
    networks: [appnet]
    volumes:
      - kafka3_data:/bitnami/kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_CLUSTER_ID=prod-messaging-cluster
      - KAFKA_KRAFT_CLUSTER_ID=prod-messaging-cluster
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT_INTERNAL://:9092,PLAINTEXT_EXTERNAL://:9094,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT_INTERNAL://kafka-3:9092,PLAINTEXT_EXTERNAL://localhost:29094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT_INTERNAL
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_CFG_MIN_INSYNC_REPLICAS=2
      - KAFKA_CFG_NUM_PARTITIONS=6
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CFG_QUOTA_WINDOW_NUM=10
      - KAFKA_CFG_QUOTA_WINDOW_SIZE_SECONDS=1
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=11534336
      - KAFKA_CFG_FETCH_MESSAGE_MAX_BYTES=11534336
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_OFFSETS_TOPIC_MIN_ISR=2
    ports:
      - "29094:9094"   # host access

  # -------------------------------
  # One-time init: topics + quotas
  # -------------------------------
  kafka-init:
    image: bitnamilegacy/kafka:3.6.2-debian-12-r17
    container_name: kafka-init
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    networks: [appnet]
    volumes:
      - ./scripts/kafka-init.sh:/scripts/kafka-init.sh:ro
    restart: "no"
    entrypoint: ["/bin/bash"]
    command:
      - -lc
      - /scripts/kafka-init.sh

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    networks: [appnet]
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
    volumes:
      - ./docker/kafka-ui/config.yml:/etc/kafkaui/dynamic_config.yaml:ro
    ports:
      - "28080:8080"

  email-worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: email-worker
    container_name: email-worker
    depends_on:
      kafka-1:
        condition: service_started
      kafka-2:
        condition: service_started
      kafka-3:
        condition: service_started
      kafka-init:
        condition: service_completed_successfully
    networks: [appnet]
    env_file:
      - .env
    environment:
      - KAFKA_BROKERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
    restart: unless-stopped
